[site]

# The canonical URL for your site, WITH a trailing slash
url = "https://news.itsjake.me/"

# Content of robots.txt
robots_txt = """
User-agent: *
Disallow: 
Disallow: /cgi-bin/"""

# Enable sitemap.xml generation. It will be added to robots.txt.
generate_sitemap = true

# Add 512KB Club "Green Team" badge to the footer if your site qualifies
# See https://512kb.club/faq
512kb_club_badge = true

[generator]

# Minify the generated HTML and CSS
minify = false
