LANG_NAMES = {
    "bs": "🇧🇦 Bosanski",
    "da": "🇩🇰 Dansk",
    "de": "🇩🇪 Deutsch",
    "el": "🇬🇷 Ελληνικά",
    "en": "🇺🇸 English",
    "es": "🇪🇸 Español",
    "fi": "🇫🇮 Suomi",
    "fr": "🇫🇷 Français",
    "he": "🇮🇱 עברית",
    "ko": "🇰🇷 한국어",
    "no": "🇳🇴 Norsk",
    "pl": "🇵🇱 Polski",
    "pt": "🇵🇹 Português",
    "ru": "🇷🇺 Русский",
    "sco": "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scots",
    "sv": "🇸🇪 Svenska",
    "vi": "🇻🇳 Tiếng Việt",
}

LANGS = [
    "bs",
    "da",
    "de",
    "el",
    "en",
    "es",
    "fi",
    "fr",
    "he",
    "ko",
    "no",
    "pl",
    "pt",
    "ru",
    "sco",
    "sv",
    "vi",
]
